### ISSUE TITLE
file type filter

### ISSUE THREAD

**Issue by gieza** [alexandrainst/node-red-contrib-ui-upload#12]
Hi, thanks for making this node public! 

It is more of a question, rather that issue. How can I add file type/extension filter to the node configuration, so that only particular file type (e.g. *.CSV) could be selected in _Open File_ dialog box?

Thanks

**Comment by Alkarex** [comment]
An `accept` attribute should be added to

https://github.com/alexandrainst/node-red-contrib-ui-upload/blob/a048bd1adef60a69f45e0ee0f5ef1c65667a41e9/ui_upload.js#L51

See https://developer.mozilla.org/docs/Web/HTML/Element/input/file

Ideally, there should be a new option to define it from the Node-RED configuration interface

Pull request welcome

**Comment by gieza** [comment]
Hello,

Thank you for explanation and great guidance on how to make a fix. If i'll find enough time, i'll make PR.

**Comment by Alkarex** [comment]
See https://github.com/alexandrainst/node-red-contrib-ui-upload/pull/15
Tests welcome
