### ISSUE TITLE
Chunk size less than 1kb

### ISSUE THREAD

**Issue by MatthieuSGMT** [alexandrainst/node-red-contrib-ui-upload#3]
Hi, thanks for your great work! 
I know that the chunk size is 1kb minimum but is there a way (by modifying ui.upload.js for example) to make the minimum chunk size in bytes instead of kilo bytes, like 128 or 256 bytes ?
Thanks! :smile:

**Comment by MatthieuSGMT** [comment]
Hi again, 
Not an issue anymore!

**Comment by Alkarex** [comment]
Ok :-)
