### ISSUE TITLE
upload fast but consume slow (ui upload + chunks to line)

### ISSUE THREAD

**Issue by akd022** [alexandrainst/node-red-contrib-ui-upload#4]
Hello, 
I am using the ui-upload & chunks-to-lines in a node-red setup and the Process is as follows:
Upload -> chunks-to-lines -> process of filtering & writing data to files -> visualize on dashboard
Where the uploaded file ~400Mbytes. & my Node-red server is not the fastest.

Case 1: 
If the upload chunk size is too big -> processing data takes long -> dashboard times out -> page refreshes & the upload stops!
Pros: upload is fast
Cons: processing gets choked & upload stops at a random points in time.
Case 2: 
If upload chunk size is too small -> uploading takes too long -> high chance of network drops & browser timeout -> upload stops
Pros: processing is not choked
Cons: upload is too slow and often times out and the whole process stops.

Case Ideal: 
Ideally, I would like..
Upload -> buffer data -> chunks to lines -> process -> visualize
So, Upload happens as fast as possible
And, Processing consumes data at its own pace thanks to the chunks to lines
Pros: Upload is fast & processing is done at server’s own pace
Cons: none!

Therefore in summary, I guess I would like the hunks-to-lines to pull data from the upload node as fast as possible but push the data in a line by line in the normal controlled manner (every time msg.tick = true).
Any tips how to achieve that?

**Comment by Alkarex** [comment]
Could you please post a picture of your flow + relevant code to better understand your cases?
Also please highlight the differences with the example documented on https://flows.nodered.org/flow/687918dd5cb66a3bfc2a661e15ef4237
