### ISSUE TITLE
This node takes over the complete ui

### ISSUE THREAD

**Issue by MikeEitel** [alexandrainst/node-red-contrib-ui-upload#5]
HI
I have the strange effect that as soon as i integrate this node into a flow the rest of my configured ui disapears.
I use W10 and no matter what browser, just this one element is on screen in ui.
Deactivate is not enough, I have to restart node-red afterwards to get the rest of my ui back.

THX in advance

**Comment by Alkarex** [comment]
Would you mind sharing a screenshot?

**Comment by MikeEitel** [comment]
How should I do this? I'm in a highly protected environment. Eventually teams for bussinesBest regards Mike EitelHuegelweg 7 8224 LoehningenSwitzerland +41 79 416 50 ***@***.*** Ursprüngliche Nachricht --------Von: Alexandre Alapetite ***@***.***>Datum: Fr., 6. Aug. 2021, 15:25An: alexandrainst/node-red-contrib-ui-upload ***@***.***>Cc: Mike Eitel ***@***.***>, Author ***@***.***>Betreff: Re: [alexandrainst/node-red-contrib-ui-upload] This node takes over the complete ui (#5)
Would you mind sharing a screenshot?

**Comment by Alkarex** [comment]
You can copy-paste a screenshot here on GitHub

**Comment by MikeEitel** [comment]
### 
![1  Flow](https://user-images.githubusercontent.com/6073720/128521259-67864b5e-1301-48b9-b4ed-4aae2621c0ce.JPG)
![2  Normal](https://user-images.githubusercontent.com/6073720/128521260-d6f0501e-25c9-4f08-b640-69848557d8a2.JPG)
![3  Layout](https://user-images.githubusercontent.com/6073720/128521263-e4cfc50c-7a2e-4393-af1e-f33c84990d66.JPG)
![4  Activate](https://user-images.githubusercontent.com/6073720/128521265-efd16ccc-da51-4200-a6de-ad4beefb2aed.JPG)
![5  Result](https://user-images.githubusercontent.com/6073720/128521266-917a16f5-0bc5-42b6-88ef-20e2eb16318b.JPG)

**Comment by MikeEitel** [comment]
By the way
The Node-Red is running on a Windows 19 SRV. 
This working pc is a W10.

**Comment by MikeEitel** [comment]
I DO NOT KNOW WHY, 
but after redoing the complete directory     node-modules    everything works like a charm.

SORRY for the inconvinience, 
but I struggled, naturally with breaks ;-), before writing this issue.
Best regards and thx for your very fast reaction !!!

**Comment by MikeEitel** [comment]
I get back the same effect when i start Node-red as a service in srv19.    Reproducable!

I use the following description:
\\Node-RED as a service according to
\\https://gist.github.com/dceejay/576b4847f0a17dc066db

\\mkdir c:\temp
\\nssm install Node-RED "c:\Users\\"%USERNAME%"\AppData\Roaming\npm\node-red.cmd"
\\nssm set Node-RED AppDirectory "c:\Users\\"%USERNAME%"\.node-red"
\\nssm set Node-RED AppParameters "-u c:\Users\\"%USERNAME%"\.node-red > c:\temp\node-red.log"

\\ This is on a system that must and can not connect to internet. The only way is the generation of an node-red infrastructure one a www connected pc and tranfer the "USER" directory en block via file zipped transfer. The result is f.x. in:
\\ C:\Users\Administrator\node_modules\.bin\node-red.cmd

cd C:\Users\Administrator\node_modules\.bin\
.\nssm install Node-RED C:\Users\Administrator\node_modules\.bin\node-red.cmd
.\nssm set Node-RED AppDirectory "c:\Users\Administrator\.node-red"
.\nssm set Node-RED AppParameters "-u c:\Users\Administrator\.node-red > c:\temp\node-red.log"
.\nssm set Node-RED Description "A wiring tool for the Internet of Things"

**Comment by Alkarex** [comment]
If you are still around, attempt of fix in https://github.com/alexandrainst/node-red-contrib-ui-upload/pull/13
Tests welcome

**Comment by MikeEitel** [comment]
Sorry, but I m in the meantime retired and have no more access to this very big enterprise cloud platform.
But Big thanks that you followed up. Super service
